<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getFindAllFoodQueryBuilder($name)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u');
        $qb
            ->andWhere('u.name LIKE :food')
            ->setParameter('food', '%'.$name.'%');

        return $qb->getQuery()->getResult();
    }

    public function getById($id)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u');
        $qb
            ->andWhere('u.id LIKE :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
