<?php

namespace AppBundle\Repository;

/**
 * SubscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribeRepository extends \Doctrine\ORM\EntityRepository
{
}
