imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    translator: ~
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   discounted.food2017@gmail.com
    password:   discounted123

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >=1.2 Possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "noreply@gmail.com"
        sender_name: "discounted"
    registration:
        form:
            type: AppBundle\Form\RegistrationFormType

easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            list:
                actions: ['edit', 'search', 'show']
                fields:
                     - email
                     - username
                     - enabled
                     - lastLogin
                     - legalEntityCode
                     - companyName
                     - addresses
            edit:
                fields:
                    - id
                    - email
                    - username
                    - legalEntityCode
                    - companyName
                    - enabled
        Address:
            class: AppBundle\Entity\Address
            list:
                actions: ['edit', 'search', 'show']
            edit:
                fields:
                    - address
                    - latitude
                    - longitude

        Product:
            class: AppBundle\Entity\Product
            list:
                actions: ['edit', 'search', 'show']
                fields:
                    - id
                    - name
                    - description
                    - dateTo
                    - dateFrom
                    - portions
                    - price
                    - address
            edit:
                fields:
                    - id
                    - name
                    - description
                    - dateTo
                    - dateFrom
                    - portions
                    - price

vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix:         /images/products
            upload_destination: %kernel.root_dir%/../web/images/products

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        address_image:
           uri_prefix:         /images/addresses
           upload_destination: %kernel.root_dir%/../web/images/addresses

           inject_on_load:     false
           delete_on_update:   true
           delete_on_remove:   true

